name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: |
          cd web/php
          composer validate --strict

      - name: Install dependencies
        run: |
          cd web/php
          composer install --prefer-dist --no-interaction --no-progress

      - name: Validate PHP cs fixer
        run: |
          cd web/php
          composer run-script php-fixer
